
# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  image: dldl/sphinx-server
  stage: deploy
  script:
  - mkdir public
  - rst2html README.rst public/index.html
  artifacts:
    paths:
    - public
  only:
  - master
